name: Check
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -e SC1091
          SHFMT_OPTS: -i 4 -d -kp
